version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t helloworld-app/Dockerfile .

     # deploy the image
     - run: docker push gcr.io/$GCP_PROJECT/front-end-app:v1 
